dist: trusty

sudo: false

language: cpp
compiler:
    - clang
cache:
    - apt

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        packages:
        - libboost-all-dev
        - cmake

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~
  - make 
  - make test
  - make install
