language: cpp
compiler:
  - g++
  # - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpng++-dev
  
addons:
	apt:
		sources:
		- ubuntu-toolchain-r-test
		- boost-latest
		packages:
		- cmake
		- g++-5
		- gcc-5

install:
	- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
	- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
		
script:
  - mkdir build
  - cd build
  - ~/bin/cmake .. -DBOOST_ROOT=$BOOST_ROOT -DCMAKE_INSTALL_PREFIX:PATH=~
  - make 
  # - make test
  - make install
