dist: trusty

sudo: false

language: cpp
compiler:
    - clang
cache:
    - apt

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        packages:
        - libboost-all-dev
        - cmake

env:
    - CONFIG=Debug
    - CONFIG=Release

script: 
    - mkdir -p build/${CONFIG}
    - cd build/${CONFIG}
    - cmake ../.. -DCMAKE_INSTALL_PREFIX:PATH=~ -DCMAKE_BUILD_TYPE=${CONFIG}
    - make
    - make test
    - make install 
