language: cpp
compiler:
    - g++
    - clang
cache:
    - apt

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        - kalakris-cmake
        packages:
        - cmake
        - g++-5
        - gcc-5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libpng++-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
        
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~
  - make 
  # - make test
  - make install
