sudo: false

language: cpp
compiler:
    - g++
    - clang
cache:
    - apt

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - boost-latest
        packages:
        - cmake
        - g++-5
        - gcc-5
        - libboost1.55-all-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi
        
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~
  - make 
  # - make test
  - make install
